### ISSUE TITLE
ERROR: the correct camera poses for current points cannot be accessed

### ISSUE THREAD

**Issue by stone100010** [Fyusion/LLFF#36]
Need to run COLMAP
Features extracted
Features matched
Sparse map created
Finished running COLMAP, see batman2/colmap_output.txt for logs
Post-colmap
Cameras 5
Images # 2
ERROR: the correct camera poses for current points cannot be accessed
Done with imgs2poses

**Comment by ShengliL** [comment]
I have the same error,any suggestion?

**Comment by stone100010** [comment]
I ended up with a colmap installation error with "Python imgs2 poses.py Fern / "can be run without error. Follow the" Official Guide to colmap "to install," apt get install colmap "may not be useful.If you have any questions, please contact me in time. I'm willing to help you as much as I can.

**Comment by stone100010** [comment]
step1:

**Comment by stone100010** [comment]
Step 1: "scenedir / images /" file structure, run as follows to get the data set made by colmap

python imgs2 poses.py <your_ scenedir>

Step 2: check that the created file directory has "fern file structure" and copy it to "nerf project file directory"

Step 3: modify "config"_ fern.txt ”Folder path and name

Step 4: clear all files under "log /", and execute "Python run"_ nerf.py --config config_ fern.txt ”At the same time, you should run "tensorboard -- logdir = logs / summaries -- port = 6006" in the same Anaconda environment and corresponding file directory!

At this point, you start the model training and tensorboard training query. The browser can use the“ localhost:6006 ”Check it out, nice~~
@ShengliL

**Comment by AbbyLuHui** [comment]
Hi @stone100010 I seem to have the same error. How did you end up solving the issue? I built colmap from source following the installation guide on the official page.

**Comment by stone100010** [comment]
window or ubunntu ? @ @AbbyLuHui

**Comment by FrankZhang0309** [comment]
@stone100010 I met the same problem on Ubuntu 18.04, Did you recompile your boost library?

**Comment by FrankZhang0309** [comment]
> Hi @stone100010 I seem to have the same error. How did you end up solving the issue? I built colmap from source following the installation guide on the official page.

I solved by 2 steps:
First, recomple boost with the same version(key point is gcc and g++ version of your system is different from  the pre-installed boost dependency)
Second, follow https://github.com/colmap/colmap/issues/513 this issue, remove the dependency of regex library of boost.

My environment is gcc 5.50, boost 1.65-1, ubuntu 18.04.

If I explained not so clearly, please let me know, I will be happy to help u.

**Comment by stone100010** [comment]
sudo apt-get install \
    git \
    cmake \
    build-essential \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-regex-dev \
    libboost-system-dev \
    libboost-test-dev \
    libeigen3-dev \
    libsuitesparse-dev \
    libfreeimage-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev


From the official website of colmap.
At the same time, I'd like to remind you to check the nvida video card driver version to see if it needs to be updated.

**Comment by stone100010** [comment]
Thank you. My problem has been solved.Others who have the same question can contact me.

**Comment by FrankZhang0309** [comment]
> Hi @stone100010 I seem to have the same error. How did you end up solving the issue? I built colmap from source following the installation guide on the official page.

I solved the exact problem with u with 3 steps:
1. recompile boost with your gcc version, mine is boost 1.65-1 and gcc 5.50
2. change the cmake boost path to make sure you are linking the right boost
3. manually recompile colmap.

But then I still met the same problem.

So I ran these three lines in terminal:
`colmap feature_extractor --database_path $DATASET_PATH/database.db --image_path $DATASET_PATH/images`

`colmap sequential_matcher --database_path $DATASET_PATH/database.db`

`colmap mapper --database_path $DATASET_PATH/databse.db --image_path $DATASET_PATH/images --output_path $DATASET_PATH/sparse
`

I found out colmap works **fine** but the database maybe **bad** which led no matching image. I changed my database, finally the code `python imgs2poses.py /path/to/your/dataset` works.

**Comment by stone100010** [comment]
well,it's a good idea!

**Comment by AbbyLuHui** [comment]
Thank you for your help! Just solved the problem.

**Comment by foocross** [comment]
> . I changed my database, finally the code `python imgs2poses.py /path/to/your/dataset` works.

Hello @FrankZhang0309 I am having the same problem. Can you give more information on "I changed my database"?. 

@AbbyLuHui can you tell how you solved the problem?

**Comment by FrankZhang0309** [comment]
@foocross  As I said, the dataset is too **bad**, so COLMAP can not match the images. So ran the three commands I mentioned to see if your images are paired.

**Comment by cuixianguang** [comment]
@FrankZhang0309 U are right. I met the same error with my own data. When I input the images of flowers provided by the author, the error disappeared.

**Comment by wilbercl** [comment]
Hello, I am running colmap and it is generating the same error that you raise, I have tried to follow the steps for the solution that they pose @stone100010 @Jiakai-Zhang  and I still have the same problem. Could someone help? Thanks!

**Comment by starhiking** [comment]
> @foocross As I said, the dataset is too **bad**, so COLMAP can not match the images. So ran the three commands I mentioned to see if your images are paired.

Hi, I have fixed the issue at https://github.com/Fyusion/LLFF/pull/60
Beside the `pose_boundary.npy` will be generated, it also will generate `view_imgs.txt` to mark which views are used.

**Comment by Yes-Jumby** [comment]
@starhiking  good job,thanks!

**Comment by hyeok-jong** [comment]
I had same ERROR  

For me it was due to ceres-solver's commits ( means version )  

Any way to fixing commit I solved.  

[fixed](https://github.com/colmap/colmap/issues/1446)

In my case, my opinion is colmap has installed but not completely.

**Comment by bearosari** [comment]
> > @foocross As I said, the dataset is too **bad**, so COLMAP can not match the images. So ran the three commands I mentioned to see if your images are paired.
> 
> Hi, I have fixed the issue at #60 Beside the `pose_boundary.npy` will be generated, it also will generate `view_imgs.txt` to mark which views are used.

Hi, I tried using your new code on poses_utils.py and it generated views_imgs.txt however I am curious as to why it always only has 2 images listed in views_imgs.txt, thus, when training, it does not match with the number of images extracted from a video input. I keep receiving an error of "Mismatch between imgs 47 and poses 2 !!!!". I hate 47 images from my dataset but only 2 produced poses. Looking forward to your reply! Thanks! :))

**Comment by cjw531** [comment]
I also had a similar problem, this is how I solved:
1. Initially ran COLMAP via `imgs2poses.py`, encountered an error
2. Removed all the binary/incorrectly formatted files in `images/` folder (i.e. I used a USB drive to transfer image files from Mac, and had DS_Store and/or `._img_1.png` like malformed files)
3. Removed colmap text file from the `images/` folder where the COLMAP was running in step no. 1
4. Re-run, got a proper result

**Comment by shreyask3107** [comment]
Hi @bmild and all authors, could this issue be addressed? Will we have to conclude that this error shall pop up for bad incompatible datasets?

I agree with @bearosari, the new pull request suggested by @starhiking does not seem to resolve the problem. It just generated two images. 

Hope to get this resolved soon. Thanks!

**Comment by harivnkochi** [comment]
I face a similar issue. Ran colmap separately and generated the binary files (cameras, images, points3D) as well as text files. Ran the subfunctions load_colmap_data() followed by save_poses using the loaded cameras, poses, perm (tried with both binary and text), but it clearly has a mismatch between number of images and the cam[ind] it is trying to access. specifically, pts3d[k].image_ids contains inds outside length of camera inds. 

I know the colmap output isnt bad or degraded because instant-ngp worked fine on this colmap output.

I'm guessing either your load_colmap_data or save_poses function may be outdated with respect to latest colmap outputs ? Please help, this is getting me stuck.
